"""Daily log generator — produces a human-readable markdown report of each trading session."""

from __future__ import annotations

from datetime import date
from pathlib import Path

LOGS_DIR = Path(__file__).parent.parent / "data" / "logs"


def generate_daily_log(
    log_date: date,
    market_data: dict,
    agent_results: dict[str, dict],
    portfolio_summaries: dict[str, dict],
) -> Path:
    """Generate a markdown daily log and save to data/logs/YYYY-MM-DD.md.

    Parameters
    ----------
    log_date
        The trading date.
    market_data
        Benchmark values: {"sp500": ..., "gold": ..., "btc": ..., "msci_world": ...}
    agent_results
        Per-agent output: {"steady-eddie": {"commentary": "...", "trades": [...]}, ...}
    portfolio_summaries
        Per-agent portfolio state: {"steady-eddie": {"cash": ..., "deployed": ..., "positions": [...]}, ...}

    Returns
    -------
    Path to the generated log file.
    """
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    path = LOGS_DIR / f"{log_date.isoformat()}.md"

    lines: list[str] = []
    lines.append(f"# Midas Daily Log — {log_date.isoformat()}\n")

    # Market overview
    lines.append("## Market Snapshot\n")
    lines.append("| Index | Value |")
    lines.append("|-------|-------|")
    for name, value in market_data.items():
        if isinstance(value, (int, float)):
            lines.append(f"| {name} | {value:,.2f} |")
    lines.append("")

    # Agent sections
    agent_display_names = {
        "steady-eddie": "Steady Eddie",
        "sharp-shooter": "Sharp Shooter",
        "satoshi": "Satoshi",
        "monsieur-forex": "Monsieur Forex",
        "goldfinger": "Goldfinger",
        "yolo-sapiens": "YOLO Sapiens",
    }

    for agent_id, result in agent_results.items():
        display_name = agent_display_names.get(agent_id, agent_id)
        lines.append(f"## {display_name}\n")

        # Commentary
        commentary = result.get("commentary", "No commentary provided.")
        lines.append(f"> {commentary}\n")

        # Trades
        trades = result.get("trades", [])
        if trades:
            lines.append("### Trades\n")
            lines.append("| Action | Ticker | Shares | Reasoning |")
            lines.append("|--------|--------|--------|-----------|")
            for t in trades:
                action = t.get("action", "?")
                ticker = t.get("ticker", "?")
                shares = t.get("shares", "?")
                reasoning = t.get("reasoning", "")
                lines.append(f"| {action} | {ticker} | {shares} | {reasoning} |")
            lines.append("")
        else:
            lines.append("*No trades today.*\n")

        # Portfolio state
        summary = portfolio_summaries.get(agent_id)
        if summary:
            lines.append("### Portfolio\n")
            lines.append(f"- **Cash:** ${summary.get('cash', 0):,.2f}")
            lines.append(f"- **Deployed:** ${summary.get('deployed', 0):,.2f}")
            positions = summary.get("positions", [])
            if positions:
                lines.append(f"- **Positions ({len(positions)}):** {', '.join(positions)}")
            lines.append("")

    # Footer
    lines.append("---\n")
    lines.append("*Generated by Midas — AI Fund Manager*\n")

    content = "\n".join(lines)
    path.write_text(content)
    return path
